# Generated by Django 6.0.6 on 2026-06-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_category_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtaskchecklist',
            old_name='description',
            new_name='text',
        ),
    ]
