# Generated by Django 6.0.6 on 2026-06-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_first_name_user_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubTaskCheckList',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
